# Generated by Django 4.1.7 on 2023-04-02 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time_lesson', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='center.center')),
            ],
        ),
    ]
